return {
  {
    "stevearc/aerial.nvim",
    opts = {
      layout = {
        default_direction = "right",
        placement = "window",
        min_width = 30,
        resize_to_content = false,
      },
      icons = {
        Array = "[] ",
        Boolean = "B ",
        Class = "C ",
        Constant = "K ",
        Constructor = "new ",
        Enum = "E ",
        EnumMember = "e ",
        Field = ". ",
        File = "file ",
        Function = "fn ",
        Interface = "I ",
        Key = "key ",
        Method = "m ",
        Module = "mod ",
        Namespace = "ns ",
        Null = "nil ",
        Number = "N ",
        Object = "obj ",
        Operator = "op ",
        Package = "pkg ",
        Property = "p ",
        String = "S ",
        Struct = "struct ",
        TypeParameter = "T ",
        Variable = "v ",
      },
      guides = {
        mid_item = "+-",
        last_item = "`-",
        nested_top = "| ",
        whitespace = "  ",
      },
    },
  },
}
